{% set version = "0.12.0" %}

package:
  name: h5netcdf
  version: {{ version }}.post1

source:
  url: https://pypi.io/packages/source/h/h5netcdf/h5netcdf-{{ version }}.tar.gz
  sha256: 6d3623f9ea46747249333792f13b515d05ff652dcec1ee436fa969bee03a8dd5
  patches:
    - 129_track_order_by_default.diff
    - 0.12.0.post1_version_bump.patch

build:
  number: 101
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - h5py

test:
  imports:
    - h5netcdf

about:
  home: https://github.com/shoyer/h5netcdf
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Pythonic interface to netCDF4 via h5py

extra:
  recipe-maintainers:
    - jhamman
    - ocefpaf
    - shoyer
    - kmuehlbauer
